import type { CrmLead } from "./types";

/** Demo pipeline leads aligned with `LeadSummary` + Mee Events taxonomy. */
export const DUMMY_LEADS: readonly CrmLead[] = [
  {
    id: "lead-demo-001",
    enquiryReferenceCode: "ENQ-24001",
    customerName: "Ananya Reddy",
    customerMobile: "+919876541001",
    eventTypeName: "Premium Candid Photography",
    eventDate: "2026-11-14",
    source: "mobile_app",
    status: "new",
    createdAt: hoursAgo(2),
    firstResponseDueAt: hoursAgo(-4),
  },
  {
    id: "lead-demo-002",
    enquiryReferenceCode: "ENQ-24002",
    customerName: "Karthik Sharma",
    customerMobile: "+919849022018",
    eventTypeName: "Wedding Events",
    eventDate: "2026-10-03",
    source: "mobile_app",
    status: "new",
    createdAt: hoursAgo(5),
    firstResponseDueAt: hoursAgo(-1),
  },
  {
    id: "lead-demo-003",
    enquiryReferenceCode: "ENQ-24003",
    customerName: "Meera Iyer",
    customerMobile: "+919000133440",
    eventTypeName: "Engagement Decor",
    eventDate: "2026-09-20",
    source: "referral",
    status: "claimed",
    ownerUserId: "employee-1",
    createdAt: hoursAgo(26),
  },
  {
    id: "lead-demo-004",
    enquiryReferenceCode: "ENQ-24004",
    customerName: "Sandeep Rao",
    customerMobile: "+919123455670",
    eventTypeName: "Corporate Event Staging",
    eventDate: "2026-08-28",
    source: "phone",
    status: "contacted",
    ownerUserId: "employee-1",
    createdAt: hoursAgo(48),
    firstRespondedAt: hoursAgo(40),
  },
  {
    id: "lead-demo-005",
    enquiryReferenceCode: "ENQ-24005",
    customerName: "Priya Nair",
    customerMobile: "+919988766120",
    eventTypeName: "Birthday Party Package",
    eventDate: "2026-09-05",
    source: "mobile_app",
    status: "contacted",
    ownerUserId: "employee-2",
    createdAt: hoursAgo(72),
    firstRespondedAt: hoursAgo(60),
  },
  {
    id: "lead-demo-006",
    enquiryReferenceCode: "ENQ-24006",
    customerName: "Rahul Verma",
    customerMobile: "+919700011882",
    eventTypeName: "Premium Stage Decorations",
    eventDate: "2026-12-12",
    source: "walk_in",
    status: "qualified",
    ownerUserId: "employee-1",
    createdAt: hoursAgo(96),
    firstRespondedAt: hoursAgo(90),
  },
  {
    id: "lead-demo-007",
    enquiryReferenceCode: "ENQ-24007",
    customerName: "Fatima Sheikh",
    customerMobile: "+919555544321",
    eventTypeName: "Nikah Reception Package",
    eventDate: "2026-10-18",
    source: "campaign",
    status: "qualified",
    ownerUserId: "employee-2",
    createdAt: hoursAgo(120),
    firstRespondedAt: hoursAgo(110),
  },
  {
    id: "lead-demo-008",
    enquiryReferenceCode: "ENQ-24008",
    customerName: "Vikram Patel",
    customerMobile: "+919333377880",
    eventTypeName: "Photography & Videography",
    eventDate: "2026-08-15",
    source: "mobile_app",
    status: "lost",
    ownerUserId: "employee-1",
    createdAt: hoursAgo(200),
    firstRespondedAt: hoursAgo(190),
  },
];

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}
