name: mee_events
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.12.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.2.0
  qr_flutter: ^4.1.0
  flutter_riverpod: ^2.6.1
  intl: ^0.20.3
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_dotenv: ^6.0.1
  http: ^1.6.0
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/hero/
    - assets/images/categories/
    - assets/images/home/banners/
    - assets/images/home/trending/
    - assets/images/vendors/
    - assets/images/subcategory/engagement/catering/
    - assets/images/subcategory/engagement/dj_lighting/
    - assets/images/subcategory/engagement/entertainment/
    - assets/images/subcategory/engagement/flower_garlands/
    - assets/images/subcategory/engagement/grand_entry/
    - assets/images/subcategory/engagement/house_decoration/
    - assets/images/subcategory/engagement/mehndi_makeup/
    - assets/images/subcategory/engagement/photography/
    - assets/images/subcategory/engagement/special_effects/
    - assets/images/subcategory/engagement/stage_decoration/
    - assets/images/subcategory/engagement/wedding_gifts/
    - assets/images/subcategory/pre_wedding/bachelor_party/
    - assets/images/subcategory/pre_wedding/backdrops/
    - assets/images/subcategory/pre_wedding/flower_garlands/
    - assets/images/subcategory/pre_wedding/haldi/
    - assets/images/subcategory/pre_wedding/house_decoration/
    - assets/images/subcategory/pre_wedding/mangalasnanam/
    - assets/images/subcategory/pre_wedding/mehndi_makeup/
    - assets/images/subcategory/pre_wedding/photography/
    - assets/images/subcategory/pre_wedding/puja_items/
    - assets/images/subcategory/pre_wedding/wedding_gifts/
    - assets/images/subcategory/mehndi/backdrops/
    - assets/images/subcategory/mehndi/catering/
    - assets/images/subcategory/mehndi/dj_lighting/
    - assets/images/subcategory/mehndi/entertainment/
    - assets/images/subcategory/mehndi/mehndi_makeup/
    - assets/images/subcategory/mehndi/photography/
    - assets/images/subcategory/mehndi/special_effects/
    - assets/images/subcategory/mehndi/tent_house/
    - assets/images/subcategory/sangeet/band_bharat/
    - assets/images/subcategory/sangeet/catering/
    - assets/images/subcategory/sangeet/dj_lighting/
    - assets/images/subcategory/sangeet/entertainment/
    - assets/images/subcategory/sangeet/flower_garlands/
    - assets/images/subcategory/sangeet/grand_entry/
    - assets/images/subcategory/sangeet/mehndi_makeup/
    - assets/images/subcategory/sangeet/photography/
    - assets/images/subcategory/sangeet/special_effects/
    - assets/images/subcategory/sangeet/stage_decoration/
    - assets/images/subcategory/sangeet/tent_house/
    - assets/images/subcategory/wedding/band_bharat/
    - assets/images/subcategory/wedding/catering/
    - assets/images/subcategory/wedding/dj_lighting/
    - assets/images/subcategory/wedding/entertainment/
    - assets/images/subcategory/wedding/flower_garlands/
    - assets/images/subcategory/wedding/grand_entry/
    - assets/images/subcategory/wedding/mandapam/
    - assets/images/subcategory/wedding/mehndi_makeup/
    - assets/images/subcategory/wedding/photography/
    - assets/images/subcategory/wedding/puja_items/
    - assets/images/subcategory/wedding/special_effects/
    - assets/images/subcategory/wedding/wedding_concepts/
    - assets/images/subcategory/wedding/wedding_gifts/
